wandb_version: 1

grid_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725908474.117777
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.15.3
      8:
      - 5
